name: jaded
version: 0.1.9
author: Demis Bellot <demis.bellot@gmail.com>
description: Port of node.js popular Jade view engine for Dart.
homepage: https://github.com/dartist/jaded
documentation: https://github.com/visionmedia/jade/blob/master/Readme.md
environment:
  sdk: ">=0.8.10+6 <2.0.0"
dependencies:
  character_parser: ">=0.1.3 < 0.2.0"
  markdown: ">=0.7.0 <0.8.0"
  node_shims: ">=0.1.3 < 0.2.0"
dev_dependencies:
  unittest: ">=0.9.3 <0.10.0"
