name: jaded
version: 0.2.1
Ã·author: Demis Bellot <demis.bellot@gmail.com>
description: Port of node.js popular Jade view engine for Dart. Checkout the PugJS site for documentation and usage
homepage: https://github.com/dartist/jaded
documentation: https://pugjs.org/ 
#https://github.com/visionmedia/jade/blob/master/Readme.md
environment:
  sdk: ">=2.3.0 <3.0.0"
dependencies:
  character_parser: ^0.3.0
  markdown: ^2.1.3
  node_shims: ^0.2.0
  sass: ^1.25.0

dev_dependencies:
  effective_dart:
  pedantic:
  test:
